# config.yaml

environment:   
  data_tables: "../RNAstructure/data_tables/"  # Path to data tables
  threads: 6  # Number of threads to use for parallel processing

global_ensemble_size: 20 # Global ensemble size for all ensemble generation algorithms


RNAStructure:
  # Path to the RNAstructure "fold" executable 
  executable: "../RNAstructure/exe/Fold-smp"
  params:
    a: "m6A"
    maxm: 75

RNAFold:
  # For RNAFold, we assume the command is available in PATH.
  executable: "RNAfold"
  params:
    max_bp_span: 0
    method: "mfe" # 'mfe' for default mode, 'p' for partition function mode 

RNASubopt:
  executable: "RNAsubopt"
  params:
    n_struc: 20 # Number of structures to generate, works only of probability-based mode
    method: "z" # 'z' Zuker suboptionals mode (default), 'p' for probability-based mode

EternaFold:
  executable: "./../EternaFold/src/contrafold"
  params:
    eternaFold_params: "../EternaFold/parameters/EternaFoldParams.v1"
    eternaFold_params_shape: "../EternaFold/parameters/EternaFoldParams_PLUS_POTENTIALS.v1"
    nsamples: 75

LinearFold:
  executable: "./../LinearFold/linearfold"
  params: 
    delta: 5.0

ct2dot:
  # Path to the RNAstructure "ct2dot" executable
  executable: "../RNAstructure/exe/ct2dot"
  params:
    st_num: 0

ShapeConversion:
  params:
    thresholds:
      high: 0.85
      medium: 0.5
      low: 0.3
    coefficients:
      high: 2.25
      medium: 1.25
      low: 0.75
      default: ""

Scoring:
  # options: A= identity score, B= semi-identity score, C= similarity score, D= matching brackets
  # see descriptions in utils.py
  score: "A"  